In [1]:
import numpy as np

In [2]:
minha_lista = [1,2,3]

In [3]:
minha_lista

[1, 2, 3]

In [4]:
np.array(minha_lista)

array([1, 2, 3])

In [5]:
minha_matriz = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
arr = np.zeros((5, 5))

In [11]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.linspace(0, 10, 2)

array([ 0., 10.])

In [15]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [16]:
np.random.rand(5)

array([0.73040853, 0.87518675, 0.88443574, 0.03205856, 0.58003208])

In [17]:
np.random.randn(5)

array([1.66738605, 1.12918364, 1.74942893, 0.56242807, 0.67259013])

In [18]:
np.random.randint(0, 100, 10)

array([ 8, 41, 57, 47, 56, 43, 56, 54, 67, 17])

In [19]:
np.random.rand(5) * 100

array([70.26954669, 31.52028275, 26.4826394 , 10.84289213, 50.8720606 ])

In [20]:
np.round(np.random.rand(5) * 100, 0)

array([ 6., 19., 68., 83., 39.])

In [21]:
arr = np.random.rand(25)

In [22]:
arr

array([0.31464275, 0.10020462, 0.79562359, 0.36168621, 0.28502936,
       0.86888176, 0.65194905, 0.74037991, 0.07989548, 0.12105673,
       0.15745078, 0.43491564, 0.24800172, 0.28211005, 0.25956805,
       0.59819689, 0.8068293 , 0.60352536, 0.07125851, 0.60183712,
       0.65569421, 0.05799547, 0.75860015, 0.03859875, 0.78833287])

In [29]:
arr = arr.reshape((5,5))

In [30]:
arr.shape

(5, 5)

In [32]:
arr.max()

0.8688817640185834

In [33]:
arr.argmax()

5

In [34]:
 arr.argmin()

23

=== Index ===

In [35]:
arr = np.arange(0, 30, 3)

In [36]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [37]:
arr[3]

9

In [38]:
arr[2:5]

array([ 6,  9, 12])

In [39]:
arr[:5]

array([ 0,  3,  6,  9, 12])

In [40]:
arr[2:]

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [41]:
arr[2:] = 100

In [42]:
arr

array([  0,   3, 100, 100, 100, 100, 100, 100, 100, 100])

In [46]:
arr = np.arange(50).reshape((5, 10))

In [47]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [48]:
arr.shape

(5, 10)

In [49]:
arr[:3][:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [51]:
arr2 = arr[:3]

In [52]:
arr2[:] = 100

In [53]:
arr

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [54]:
arr2 = arr[:3].copy()

In [55]:
arr2[:] = 10

In [57]:
arr2

array([[10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]])

In [59]:
arr[1:4, 5:]

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [ 35,  36,  37,  38,  39]])

In [62]:
bol = arr > 50

In [63]:
arr[bol]

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100])

In [68]:
array = np.linspace(0, 100, 30)

In [70]:
array.shape

(30,)

In [71]:
array = array.reshape(3, 10)

In [72]:
array

array([[  0.        ,   3.44827586,   6.89655172,  10.34482759,
         13.79310345,  17.24137931,  20.68965517,  24.13793103,
         27.5862069 ,  31.03448276],
       [ 34.48275862,  37.93103448,  41.37931034,  44.82758621,
         48.27586207,  51.72413793,  55.17241379,  58.62068966,
         62.06896552,  65.51724138],
       [ 68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
         82.75862069,  86.20689655,  89.65517241,  93.10344828,
         96.55172414, 100.        ]])

In [73]:
array[0:2, 2]

array([ 6.89655172, 41.37931034])